# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19eOFbHDUJFVzVCl-G6a1cgTYA4bqZBDj
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/bi.csv", encoding='latin1')

print("==== Dataset Info ====")
print(df.info())
print("\n==== First 5 Rows ====")
print(df.head())
print("\n==== Missing Values ====")
print(df.isnull().sum())

le = LabelEncoder()
for col in ['gender', 'country', 'residence', 'prevEducation']:
    df[col] = le.fit_transform(df[col])

X = df.drop(columns=['fNAME', 'lNAME'])  # Drop names
y = (df['entryEXAM'] >= 50).astype(int)

model = RandomForestClassifier(random_state=42)
model.fit(X, y)
y_pred = model.predict(X)

model = RandomForestClassifier(random_state=42)
model.fit(X, y)
y_pred = model.predict(X)

print("\n==== Accuracy ====")
print(accuracy_score(y, y_pred))

print("\n==== Classification Report ====")
print(classification_report(y, y_pred))

print("\n==== Confusion Matrix ====")
print(confusion_matrix(y, y_pred))

feat_importance = pd.Series(model.feature_importances_, index=X.columns)
feat_importance.nlargest(10).plot(kind='barh')
plt.title("Top 10 Feature Importances")
plt.show()